// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareWatch

#ifndef _SQUAREWATCH_UI_H
#define _SQUAREWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void BeatPlay_Animation(lv_obj_t * TargetObject, int delay);
void Pulse_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_BeatCont;
extern lv_obj_t * ui_Beat1;
extern lv_obj_t * ui_Beat2;
extern lv_obj_t * ui_Beat3;
extern lv_obj_t * ui_Heart1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_grid_png);    // assets/grid.png
LV_IMG_DECLARE(ui_img_ecg_png);    // assets/ecg.png
LV_IMG_DECLARE(ui_img_heart_png);    // assets/heart.png
LV_IMG_DECLARE(ui_img_x_png);    // assets/x.png
LV_IMG_DECLARE(ui_img_house_png);    // assets/house.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
