// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareWatch

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image7, &ui_img_grid_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 212
    lv_obj_set_x(ui_Image7, 14);
    lv_obj_set_y(ui_Image7, 0);
    lv_obj_set_align(ui_Image7, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_grid_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 212
    lv_obj_set_x(ui_Image1, -14);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image1, 1800);

    ui_BeatCont = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_BeatCont);
    lv_obj_set_width(ui_BeatCont, 318);
    lv_obj_set_height(ui_BeatCont, 128);
    lv_obj_set_align(ui_BeatCont, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_BeatCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Beat1 = lv_img_create(ui_BeatCont);
    lv_img_set_src(ui_Beat1, &ui_img_ecg_png);
    lv_obj_set_width(ui_Beat1, 106);
    lv_obj_set_height(ui_Beat1, 91);
    lv_obj_set_x(ui_Beat1, -105);
    lv_obj_set_y(ui_Beat1, -21);
    lv_obj_set_align(ui_Beat1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Beat1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Beat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Beat2 = lv_img_create(ui_BeatCont);
    lv_img_set_src(ui_Beat2, &ui_img_ecg_png);
    lv_obj_set_width(ui_Beat2, 106);
    lv_obj_set_height(ui_Beat2, 91);
    lv_obj_set_x(ui_Beat2, 1);
    lv_obj_set_y(ui_Beat2, -21);
    lv_obj_set_align(ui_Beat2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Beat2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Beat2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Beat3 = lv_img_create(ui_BeatCont);
    lv_img_set_src(ui_Beat3, &ui_img_ecg_png);
    lv_obj_set_width(ui_Beat3, 106);
    lv_obj_set_height(ui_Beat3, 91);
    lv_obj_set_x(ui_Beat3, 107);
    lv_obj_set_y(ui_Beat3, -21);
    lv_obj_set_align(ui_Beat3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Beat3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Beat3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Heart1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Heart1, &ui_img_heart_png);
    lv_obj_set_width(ui_Heart1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Heart1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Heart1, -46);
    lv_obj_set_y(ui_Heart1, 48);
    lv_obj_set_align(ui_Heart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Heart1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Heart1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -3);
    lv_obj_set_y(ui_Label1, 49);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "63bpm");

    ui_Image13 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image13, &ui_img_x_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 13
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_Image13, 50);
    lv_obj_set_y(ui_Image13, -56);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image14, &ui_img_house_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_Image14, 46);
    lv_obj_set_y(ui_Image14, 46);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
